name: rubocop-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: RuboCop Linter Action
        uses: andrewmcodes-archive/rubocop-linter-action@v3.3.0
